# Generated by Django 3.1 on 2020-10-02 14:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200923_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
