# Generated by Django 3.1 on 2020-10-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_big_event',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Etkinlik Posteri'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('sponsorship_type', models.CharField(choices=[('altın', 'ALTIN'), ('gümüş', 'GÜMÜŞ'), ('bronz', 'BRONZ'), ('ürün', 'ÜRÜN'), ('destek', 'DESTEK'), ('medya', 'MEDYA')], max_length=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Konuşmacının adı')),
                ('bio', models.TextField(verbose_name='Konuşmacı hakkında bilgi')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Konuşmacının resmi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='event.event')),
            ],
        ),
    ]
