# Generated by Django 3.1 on 2020-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201006_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Sponsorun adı'),
        ),
    ]
