# Generated by Django 3.1 on 2020-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201006_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_big_event',
        ),
        migrations.AddField(
            model_name='event',
            name='distinct_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='distinct_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
