# Generated by Django 3.1 on 2020-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201008_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='iframe linki'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google maps linki'),
        ),
    ]
