# Generated by Django 3.1 on 2020-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20201008_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='iframe_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='iframe linki'),
        ),
    ]
