# Generated by Django 3.1 on 2020-10-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20201008_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
