# Generated by Django 3.1 on 2020-10-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_delete_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SilverSponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='MediaSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MediaSponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='MainSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainSponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemSponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='GoldSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GoldSponsor', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='BronzeSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sponsorun adı')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sponsorun logosu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BronzeSponsor', to='event.event')),
            ],
        ),
    ]
