# Generated by Django 3.1 on 2020-10-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_bronzesponsor_goldsponsor_itemsponsor_mainsponsor_mediasponsor_silversponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzesponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
        migrations.AddField(
            model_name='goldsponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
        migrations.AddField(
            model_name='itemsponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
        migrations.AddField(
            model_name='mainsponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
        migrations.AddField(
            model_name='mediasponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
        migrations.AddField(
            model_name='silversponsor',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sponsor Sayfasının Linki'),
        ),
    ]
