# Generated by Django 3.1 on 2020-10-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20201009_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Speaker', to='event.event'),
        ),
    ]
